- {filename: 'dumpster.png', position: { x: 0.276, y: -12.2}, quaternion: {r1: 0, r2: 0, r3: -0.628, r4: 0.778}}
- {filename: 'cube_20k.png', position: { x: -2.82, y: -2.83}, quaternion: {r1: 0, r2: 0, r3: 0.936, r4: 0.353}}
- {filename: 'bookshelf.png', position: { x: 4.32, y: -2.42}, quaternion: {r1: 0, r2: 0, r3: 0.904, r4: -0.427}}
